"""LLM provider abstract interface and data structures."""

from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class LLMToolCall(BaseModel):
    id: str = Field(default="", description="Unique ID of the tool call")
    name: str = Field(..., description="Function/tool name to execute")
    arguments: Dict[str, Any] = Field(
        default_factory=dict, description="Parsed arguments dictionary"
    )


class LLMMessage(BaseModel):
    role: str = Field(..., description="Role: 'system', 'user', 'assistant', or 'tool'")
    content: Optional[str] = Field(default=None, description="Text content of message")
    tool_calls: Optional[List[LLMToolCall]] = Field(
        default=None, description="Tool calls generated by model"
    )
    tool_call_id: Optional[str] = Field(
        default=None, description="Referenced tool call ID for tool role"
    )
    name: Optional[str] = Field(default=None, description="Name of the tool if role is 'tool'")


class LLMResponse(BaseModel):
    content: Optional[str] = Field(default=None, description="Generated assistant message text")
    tool_calls: Optional[List[LLMToolCall]] = Field(
        default=None, description="Discovered tool calls to invoke"
    )
    finish_reason: Optional[str] = Field(
        default=None, description="Completion reason (e.g. stop, tool_calls)"
    )
    model: str = Field(default="", description="Model name that generated the response")
    duration_seconds: float = Field(default=0.0, description="Latency in seconds")
    prompt_tokens: Optional[int] = None
    completion_tokens: Optional[int] = None


class LLMProvider(ABC):
    """Abstract base class for LLM providers."""

    model: str = ""

    @abstractmethod
    async def generate(self, messages: List[LLMMessage], **kwargs: Any) -> LLMResponse:
        """Generate response without tool definitions."""
        pass

    @abstractmethod
    async def generate_with_tools(
        self,
        messages: List[LLMMessage],
        tools: List[Dict[str, Any]],
        **kwargs: Any,
    ) -> LLMResponse:
        """Generate response with tool definitions for function calling."""
        pass

    @abstractmethod
    async def health_check(self) -> bool:
        """Verify reachability and status of the LLM service."""
        pass
